[keyboard]
name = "alps80"
product_name = "alps80"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[matrix]
input_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
output_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11", "PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_26",  "PIN_27", "PIN_28"]

[layout]
rows = 8
cols = 11
layers = 2
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (1,6) (2,6) (0,7) (0,8) (1,8) (2,8) (3,8) (7,10)
(1,0) (1,1) (1,2) (1,3) (1,4) (2,4) (1,5) (2,5) (3,6) (1,7) (2,7) (0,9) (1,9) (2,9) (4,8)
(2,0) (2,1) (2,2) (3,2) (2,3) (3,4) (4,4) (3,5) (4,5) (4,6) (3,7) (3,9) (4,9) (5,8)
(0,10) (3,1) (4,1) (4,2) (5,2) (3,3) (4,3) (5,4) (6,4) (5,5) (5,6) (4,7) (5,9)
(3,0) (2,10) (5,1) (6,1) (7,1) (6,2) (7,2) (5,3) (6,3) (7,4) (6,5) (6,6) (5,7) (3,10)
(4,0) (5,0) (6,0) (1,10) (7,3) (7,6) (6,7) (6,9) (6,8)
"""

[[layer]]
name = "base"
keys = """
F11 F1 F2 F3 F4 F5 F6 F7 F8 Home Up Down Left Right F12
Escape Kc1 Kc2 Kc3 Kc4 Kc5 Kc6 Kc7 Kc8 Kc9 Kc0 Minus Equal Backslash Backspace
Tab Q W E R T Y U I O P LeftBracket RightBracket Enter
LCtrl A S D F G H J K L Semicolon Quote Grave
CapsLock LShift Z X C V B N M Comma Dot Slash NonusBackslash RShift
F9 LCtrl LAlt LGui Space NumLock Insert Delete F10
"""
